# Generated by Django 5.1.2 on 2025-10-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="stripe_payment_intent_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачено"),
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
